<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <AssemblyName>BlazingOrchard.Components</AssemblyName>
    <RootNamespace>BlazingOrchard.Components</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Themes\**;Themes.broken\**;.Themes.broken\**" />
    <Content Remove="Themes\**;Themes.broken\**;.Themes.broken\**" />
    <EmbeddedResource Remove="Themes\**;Themes.broken\**;.Themes.broken\**" />
    <None Remove="Themes\**;Themes.broken\**;.Themes.broken\**" />
    <RazorGenerate Remove="Themes\**;Themes.broken\**;.Themes.broken\**" />
    <RazorComponent Remove="Themes\**;Themes.broken\**;.Themes.broken\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Radzen.Blazor" />
  </ItemGroup>

  <ItemGroup Condition="'$(RuntimeIdentifier)' != 'browser-wasm' and '$(SkipBlazingOrchardAdminWasmBuild)' != 'true'">
    <ProjectReference Include="Themes\BlazingOrchard.Admin\BlazingOrchard.Admin.csproj" />
    <ProjectReference Include="Themes\BlazingOrchard.Site\BlazingOrchard.Site.csproj" />
  </ItemGroup>

  <Target Name="BuildBlazingOrchardAdminWasm" AfterTargets="Build" Condition="'$(SkipBlazingOrchardAdminWasmBuild)' != 'true' and '$(DesignTimeBuild)' != 'true'">
    <Exec Command="dotnet restore &quot;$(MSBuildProjectDirectory)\Themes\BlazingOrchard.Admin\wasm\BlazingOrchard.Admin.Wasm.csproj&quot; /p:SkipBlazingOrchardAdminWasmBuild=true" />
    <Exec Command="dotnet build &quot;$(MSBuildProjectDirectory)\Themes\BlazingOrchard.Admin\wasm\BlazingOrchard.Admin.Wasm.csproj&quot; --no-restore --configuration $(Configuration) /p:SkipBlazingOrchardAdminWasmBuild=true" />
  </Target>
</Project>
