namespace Crest.Migrations;

// Reference data for the shared global lists beyond countries and units of measure
// (which live in GlobalContentPartListsMigrations). Same rules apply everywhere:
// keys are the stable machine contract, labels are tenant-renamable seeds, Value is
// the second machine datum where the key alone is not enough, and SeedAsync only
// ever ADDS - corrections to already-seeded rows need their own migration step.
internal static class GlobalReferenceData
{
    /// <summary>
    /// ITU E.164 dial codes by ISO 3166-1 alpha-2 country. The COUNTRY is the key
    /// (dial codes are not unique - +1 spans the whole NANP); the dial code is the
    /// machine Value. NANP members carry their area-code prefix as "+1-XXX".
    /// Countries without an assigned public dial code (AQ, BV, GS, HM, TF, UM, PN)
    /// are simply absent - absence means "no dial code", not zero.
    /// </summary>
    internal static readonly (string Code, string DialCode)[] DialCodes =
    [
        ("AD", "+376"), ("AE", "+971"), ("AF", "+93"), ("AG", "+1-268"), ("AI", "+1-264"),
        ("AL", "+355"), ("AM", "+374"), ("AO", "+244"), ("AR", "+54"), ("AS", "+1-684"),
        ("AT", "+43"), ("AU", "+61"), ("AW", "+297"), ("AX", "+358"), ("AZ", "+994"),
        ("BA", "+387"), ("BB", "+1-246"), ("BD", "+880"), ("BE", "+32"), ("BF", "+226"),
        ("BG", "+359"), ("BH", "+973"), ("BI", "+257"), ("BJ", "+229"), ("BL", "+590"),
        ("BM", "+1-441"), ("BN", "+673"), ("BO", "+591"), ("BQ", "+599"), ("BR", "+55"),
        ("BS", "+1-242"), ("BT", "+975"), ("BW", "+267"), ("BY", "+375"), ("BZ", "+501"),
        ("CA", "+1"), ("CC", "+61"), ("CD", "+243"), ("CF", "+236"), ("CG", "+242"),
        ("CH", "+41"), ("CI", "+225"), ("CK", "+682"), ("CL", "+56"), ("CM", "+237"),
        ("CN", "+86"), ("CO", "+57"), ("CR", "+506"), ("CU", "+53"), ("CV", "+238"),
        ("CW", "+599"), ("CX", "+61"), ("CY", "+357"), ("CZ", "+420"), ("DE", "+49"),
        ("DJ", "+253"), ("DK", "+45"), ("DM", "+1-767"), ("DO", "+1-809"), ("DZ", "+213"),
        ("EC", "+593"), ("EE", "+372"), ("EG", "+20"), ("EH", "+212"), ("ER", "+291"),
        ("ES", "+34"), ("ET", "+251"), ("FI", "+358"), ("FJ", "+679"), ("FK", "+500"),
        ("FM", "+691"), ("FO", "+298"), ("FR", "+33"), ("GA", "+241"), ("GB", "+44"),
        ("GD", "+1-473"), ("GE", "+995"), ("GF", "+594"), ("GG", "+44"), ("GH", "+233"),
        ("GI", "+350"), ("GL", "+299"), ("GM", "+220"), ("GN", "+224"), ("GP", "+590"),
        ("GQ", "+240"), ("GR", "+30"), ("GT", "+502"), ("GU", "+1-671"), ("GW", "+245"),
        ("GY", "+592"), ("HK", "+852"), ("HN", "+504"), ("HR", "+385"), ("HT", "+509"),
        ("HU", "+36"), ("ID", "+62"), ("IE", "+353"), ("IL", "+972"), ("IM", "+44"),
        ("IN", "+91"), ("IO", "+246"), ("IQ", "+964"), ("IR", "+98"), ("IS", "+354"),
        ("IT", "+39"), ("JE", "+44"), ("JM", "+1-876"), ("JO", "+962"), ("JP", "+81"),
        ("KE", "+254"), ("KG", "+996"), ("KH", "+855"), ("KI", "+686"), ("KM", "+269"),
        ("KN", "+1-869"), ("KP", "+850"), ("KR", "+82"), ("KW", "+965"), ("KY", "+1-345"),
        ("KZ", "+7"), ("LA", "+856"), ("LB", "+961"), ("LC", "+1-758"), ("LI", "+423"),
        ("LK", "+94"), ("LR", "+231"), ("LS", "+266"), ("LT", "+370"), ("LU", "+352"),
        ("LV", "+371"), ("LY", "+218"), ("MA", "+212"), ("MC", "+377"), ("MD", "+373"),
        ("ME", "+382"), ("MF", "+590"), ("MG", "+261"), ("MH", "+692"), ("MK", "+389"),
        ("ML", "+223"), ("MM", "+95"), ("MN", "+976"), ("MO", "+853"), ("MP", "+1-670"),
        ("MQ", "+596"), ("MR", "+222"), ("MS", "+1-664"), ("MT", "+356"), ("MU", "+230"),
        ("MV", "+960"), ("MW", "+265"), ("MX", "+52"), ("MY", "+60"), ("MZ", "+258"),
        ("NA", "+264"), ("NC", "+687"), ("NE", "+227"), ("NF", "+672"), ("NG", "+234"),
        ("NI", "+505"), ("NL", "+31"), ("NO", "+47"), ("NP", "+977"), ("NR", "+674"),
        ("NU", "+683"), ("NZ", "+64"), ("OM", "+968"), ("PA", "+507"), ("PE", "+51"),
        ("PF", "+689"), ("PG", "+675"), ("PH", "+63"), ("PK", "+92"), ("PL", "+48"),
        ("PM", "+508"), ("PR", "+1-787"), ("PS", "+970"), ("PT", "+351"), ("PW", "+680"),
        ("PY", "+595"), ("QA", "+974"), ("RE", "+262"), ("RO", "+40"), ("RS", "+381"),
        ("RU", "+7"), ("RW", "+250"), ("SA", "+966"), ("SB", "+677"), ("SC", "+248"),
        ("SD", "+249"), ("SE", "+46"), ("SG", "+65"), ("SH", "+290"), ("SI", "+386"),
        ("SJ", "+47"), ("SK", "+421"), ("SL", "+232"), ("SM", "+378"), ("SN", "+221"),
        ("SO", "+252"), ("SR", "+597"), ("SS", "+211"), ("ST", "+239"), ("SV", "+503"),
        ("SX", "+1-721"), ("SY", "+963"), ("SZ", "+268"), ("TC", "+1-649"), ("TD", "+235"),
        ("TG", "+228"), ("TH", "+66"), ("TJ", "+992"), ("TK", "+690"), ("TL", "+670"),
        ("TM", "+993"), ("TN", "+216"), ("TO", "+676"), ("TR", "+90"), ("TT", "+1-868"),
        ("TV", "+688"), ("TW", "+886"), ("TZ", "+255"), ("UA", "+380"), ("UG", "+256"),
        ("US", "+1"), ("UY", "+598"), ("UZ", "+998"), ("VA", "+39"), ("VC", "+1-784"),
        ("VE", "+58"), ("VG", "+1-284"), ("VI", "+1-340"), ("VN", "+84"), ("VU", "+678"),
        ("WF", "+681"), ("WS", "+685"), ("YE", "+967"), ("YT", "+262"), ("ZA", "+27"),
        ("ZM", "+260"), ("ZW", "+263"),
    ];

    /// <summary>
    /// Postal-code validation patterns by ISO country, for countries with a defined,
    /// widely-used format (CLDR/UPU-derived). The pattern is the machine Value; a
    /// country that is absent either has no postal codes or no stable format.
    /// Patterns are anchored, case-insensitive matching is the CONSUMER's choice.
    /// </summary>
    internal static readonly (string Code, string Pattern)[] PostalFormats =
    [
        ("AD", @"^AD\d{3}$"),
        ("AR", @"^[A-Z]\d{4}[A-Z]{3}$"),
        ("AT", @"^\d{4}$"),
        ("AU", @"^\d{4}$"),
        ("AZ", @"^AZ ?\d{4}$"),
        ("BD", @"^\d{4}$"),
        ("BE", @"^\d{4}$"),
        ("BG", @"^\d{4}$"),
        ("BR", @"^\d{5}-?\d{3}$"),
        ("BY", @"^\d{6}$"),
        ("CA", @"^[A-Za-z]\d[A-Za-z] ?\d[A-Za-z]\d$"),
        ("CH", @"^\d{4}$"),
        ("CL", @"^\d{7}$"),
        ("CN", @"^\d{6}$"),
        ("CO", @"^\d{6}$"),
        ("CR", @"^\d{5}$"),
        ("CY", @"^\d{4}$"),
        ("CZ", @"^\d{3} ?\d{2}$"),
        ("DE", @"^\d{5}$"),
        ("DK", @"^\d{4}$"),
        ("DO", @"^\d{5}$"),
        ("DZ", @"^\d{5}$"),
        ("EC", @"^\d{6}$"),
        ("EE", @"^\d{5}$"),
        ("EG", @"^\d{5}$"),
        ("ES", @"^\d{5}$"),
        ("ET", @"^\d{4}$"),
        ("FI", @"^\d{5}$"),
        ("FO", @"^\d{3}$"),
        ("FR", @"^\d{5}$"),
        ("GB", @"^[A-Za-z]{1,2}\d[A-Za-z\d]? ?\d[A-Za-z]{2}$"),
        ("GE", @"^\d{4}$"),
        ("GL", @"^\d{4}$"),
        ("GR", @"^\d{3} ?\d{2}$"),
        ("GT", @"^\d{5}$"),
        ("HR", @"^\d{5}$"),
        ("HT", @"^\d{4}$"),
        ("HU", @"^\d{4}$"),
        ("ID", @"^\d{5}$"),
        ("IE", @"^[A-Za-z]\d{2} ?[A-Za-z\d]{4}$"),
        ("IL", @"^\d{7}$"),
        ("IN", @"^\d{6}$"),
        ("IQ", @"^\d{5}$"),
        ("IR", @"^\d{5}-?\d{5}$"),
        ("IS", @"^\d{3}$"),
        ("IT", @"^\d{5}$"),
        ("JO", @"^\d{5}$"),
        ("JP", @"^\d{3}-?\d{4}$"),
        ("KE", @"^\d{5}$"),
        ("KG", @"^\d{6}$"),
        ("KH", @"^\d{5,6}$"),
        ("KR", @"^\d{5}$"),
        ("KW", @"^\d{5}$"),
        ("KZ", @"^\d{6}$"),
        ("LA", @"^\d{5}$"),
        ("LB", @"^\d{4}( ?\d{4})?$"),
        ("LI", @"^\d{4}$"),
        ("LK", @"^\d{5}$"),
        ("LT", @"^LT-?\d{5}$"),
        ("LU", @"^\d{4}$"),
        ("LV", @"^LV-?\d{4}$"),
        ("MA", @"^\d{5}$"),
        ("MC", @"^980\d{2}$"),
        ("MD", @"^MD-?\d{4}$"),
        ("ME", @"^\d{5}$"),
        ("MK", @"^\d{4}$"),
        ("MN", @"^\d{5}$"),
        ("MT", @"^[A-Za-z]{3} ?\d{4}$"),
        ("MX", @"^\d{5}$"),
        ("MY", @"^\d{5}$"),
        ("MZ", @"^\d{4}$"),
        ("NG", @"^\d{6}$"),
        ("NI", @"^\d{5}$"),
        ("NL", @"^\d{4} ?[A-Za-z]{2}$"),
        ("NO", @"^\d{4}$"),
        ("NP", @"^\d{5}$"),
        ("NZ", @"^\d{4}$"),
        ("PE", @"^\d{5}$"),
        ("PH", @"^\d{4}$"),
        ("PK", @"^\d{5}$"),
        ("PL", @"^\d{2}-?\d{3}$"),
        ("PT", @"^\d{4}-?\d{3}$"),
        ("PY", @"^\d{4}$"),
        ("RO", @"^\d{6}$"),
        ("RS", @"^\d{5}$"),
        ("RU", @"^\d{6}$"),
        ("SA", @"^\d{5}(-?\d{4})?$"),
        ("SE", @"^\d{3} ?\d{2}$"),
        ("SG", @"^\d{6}$"),
        ("SI", @"^\d{4}$"),
        ("SK", @"^\d{3} ?\d{2}$"),
        ("SM", @"^4789\d$"),
        ("SN", @"^\d{5}$"),
        ("SV", @"^\d{4}$"),
        ("TH", @"^\d{5}$"),
        ("TN", @"^\d{4}$"),
        ("TR", @"^\d{5}$"),
        ("TW", @"^\d{3}(\d{2,3})?$"),
        ("TZ", @"^\d{5}$"),
        ("UA", @"^\d{5}$"),
        ("US", @"^\d{5}(-\d{4})?$"),
        ("UY", @"^\d{5}$"),
        ("UZ", @"^\d{6}$"),
        ("VA", @"^00120$"),
        ("VN", @"^\d{5}$"),
        ("ZA", @"^\d{4}$"),
        ("ZM", @"^\d{5}$"),
    ];

    /// <summary>ISO 639-1 two-letter language codes, English reference names.</summary>
    internal static readonly (string Code, string Name)[] Languages =
    [
        ("aa", "Afar"), ("ab", "Abkhazian"), ("ae", "Avestan"), ("af", "Afrikaans"),
        ("ak", "Akan"), ("am", "Amharic"), ("an", "Aragonese"), ("ar", "Arabic"),
        ("as", "Assamese"), ("av", "Avaric"), ("ay", "Aymara"), ("az", "Azerbaijani"),
        ("ba", "Bashkir"), ("be", "Belarusian"), ("bg", "Bulgarian"), ("bi", "Bislama"),
        ("bm", "Bambara"), ("bn", "Bengali"), ("bo", "Tibetan"), ("br", "Breton"),
        ("bs", "Bosnian"), ("ca", "Catalan"), ("ce", "Chechen"), ("ch", "Chamorro"),
        ("co", "Corsican"), ("cr", "Cree"), ("cs", "Czech"), ("cu", "Church Slavic"),
        ("cv", "Chuvash"), ("cy", "Welsh"), ("da", "Danish"), ("de", "German"),
        ("dv", "Divehi"), ("dz", "Dzongkha"), ("ee", "Ewe"), ("el", "Greek"),
        ("en", "English"), ("eo", "Esperanto"), ("es", "Spanish"), ("et", "Estonian"),
        ("eu", "Basque"), ("fa", "Persian"), ("ff", "Fulah"), ("fi", "Finnish"),
        ("fj", "Fijian"), ("fo", "Faroese"), ("fr", "French"), ("fy", "Western Frisian"),
        ("ga", "Irish"), ("gd", "Scottish Gaelic"), ("gl", "Galician"), ("gn", "Guarani"),
        ("gu", "Gujarati"), ("gv", "Manx"), ("ha", "Hausa"), ("he", "Hebrew"),
        ("hi", "Hindi"), ("ho", "Hiri Motu"), ("hr", "Croatian"), ("ht", "Haitian Creole"),
        ("hu", "Hungarian"), ("hy", "Armenian"), ("hz", "Herero"), ("ia", "Interlingua"),
        ("id", "Indonesian"), ("ie", "Interlingue"), ("ig", "Igbo"), ("ii", "Sichuan Yi"),
        ("ik", "Inupiaq"), ("io", "Ido"), ("is", "Icelandic"), ("it", "Italian"),
        ("iu", "Inuktitut"), ("ja", "Japanese"), ("jv", "Javanese"), ("ka", "Georgian"),
        ("kg", "Kongo"), ("ki", "Kikuyu"), ("kj", "Kuanyama"), ("kk", "Kazakh"),
        ("kl", "Kalaallisut"), ("km", "Khmer"), ("kn", "Kannada"), ("ko", "Korean"),
        ("kr", "Kanuri"), ("ks", "Kashmiri"), ("ku", "Kurdish"), ("kv", "Komi"),
        ("kw", "Cornish"), ("ky", "Kyrgyz"), ("la", "Latin"), ("lb", "Luxembourgish"),
        ("lg", "Ganda"), ("li", "Limburgish"), ("ln", "Lingala"), ("lo", "Lao"),
        ("lt", "Lithuanian"), ("lu", "Luba-Katanga"), ("lv", "Latvian"), ("mg", "Malagasy"),
        ("mh", "Marshallese"), ("mi", "Maori"), ("mk", "Macedonian"), ("ml", "Malayalam"),
        ("mn", "Mongolian"), ("mr", "Marathi"), ("ms", "Malay"), ("mt", "Maltese"),
        ("my", "Burmese"), ("na", "Nauru"), ("nb", "Norwegian Bokmål"), ("nd", "North Ndebele"),
        ("ne", "Nepali"), ("ng", "Ndonga"), ("nl", "Dutch"), ("nn", "Norwegian Nynorsk"),
        ("no", "Norwegian"), ("nr", "South Ndebele"), ("nv", "Navajo"), ("ny", "Chichewa"),
        ("oc", "Occitan"), ("oj", "Ojibwa"), ("om", "Oromo"), ("or", "Odia"),
        ("os", "Ossetian"), ("pa", "Punjabi"), ("pi", "Pali"), ("pl", "Polish"),
        ("ps", "Pashto"), ("pt", "Portuguese"), ("qu", "Quechua"), ("rm", "Romansh"),
        ("rn", "Rundi"), ("ro", "Romanian"), ("ru", "Russian"), ("rw", "Kinyarwanda"),
        ("sa", "Sanskrit"), ("sc", "Sardinian"), ("sd", "Sindhi"), ("se", "Northern Sami"),
        ("sg", "Sango"), ("si", "Sinhala"), ("sk", "Slovak"), ("sl", "Slovenian"),
        ("sm", "Samoan"), ("sn", "Shona"), ("so", "Somali"), ("sq", "Albanian"),
        ("sr", "Serbian"), ("ss", "Swati"), ("st", "Southern Sotho"), ("su", "Sundanese"),
        ("sv", "Swedish"), ("sw", "Swahili"), ("ta", "Tamil"), ("te", "Telugu"),
        ("tg", "Tajik"), ("th", "Thai"), ("ti", "Tigrinya"), ("tk", "Turkmen"),
        ("tl", "Tagalog"), ("tn", "Tswana"), ("to", "Tongan"), ("tr", "Turkish"),
        ("ts", "Tsonga"), ("tt", "Tatar"), ("tw", "Twi"), ("ty", "Tahitian"),
        ("ug", "Uyghur"), ("uk", "Ukrainian"), ("ur", "Urdu"), ("uz", "Uzbek"),
        ("ve", "Venda"), ("vi", "Vietnamese"), ("vo", "Volapük"), ("wa", "Walloon"),
        ("wo", "Wolof"), ("xh", "Xhosa"), ("yi", "Yiddish"), ("yo", "Yoruba"),
        ("za", "Zhuang"), ("zh", "Chinese"), ("zu", "Zulu"),
    ];

    /// <summary>
    /// Geographic US area codes (NANP), Category = state/territory name. US-only by
    /// ruling; Canada/Caribbean NANP members are a separate decision. Overlays are
    /// added a few times a year - module reseeds are the update path (adds only).
    /// </summary>
    internal static readonly (string Code, string State)[] UsAreaCodes =
    [
        ("205", "Alabama"), ("251", "Alabama"), ("256", "Alabama"), ("334", "Alabama"), ("659", "Alabama"), ("938", "Alabama"),
        ("907", "Alaska"),
        ("480", "Arizona"), ("520", "Arizona"), ("602", "Arizona"), ("623", "Arizona"), ("928", "Arizona"),
        ("479", "Arkansas"), ("501", "Arkansas"), ("870", "Arkansas"),
        ("209", "California"), ("213", "California"), ("279", "California"), ("310", "California"), ("323", "California"),
        ("341", "California"), ("350", "California"), ("408", "California"), ("415", "California"), ("424", "California"),
        ("442", "California"), ("510", "California"), ("530", "California"), ("559", "California"), ("562", "California"),
        ("619", "California"), ("626", "California"), ("628", "California"), ("650", "California"), ("657", "California"),
        ("661", "California"), ("669", "California"), ("707", "California"), ("714", "California"), ("747", "California"),
        ("760", "California"), ("805", "California"), ("818", "California"), ("820", "California"), ("831", "California"),
        ("840", "California"), ("858", "California"), ("909", "California"), ("916", "California"), ("925", "California"),
        ("949", "California"), ("951", "California"),
        ("303", "Colorado"), ("719", "Colorado"), ("720", "Colorado"), ("970", "Colorado"), ("983", "Colorado"),
        ("203", "Connecticut"), ("475", "Connecticut"), ("860", "Connecticut"), ("959", "Connecticut"),
        ("302", "Delaware"),
        ("202", "District of Columbia"), ("771", "District of Columbia"),
        ("239", "Florida"), ("305", "Florida"), ("321", "Florida"), ("352", "Florida"), ("386", "Florida"),
        ("407", "Florida"), ("561", "Florida"), ("689", "Florida"), ("727", "Florida"), ("754", "Florida"),
        ("772", "Florida"), ("786", "Florida"), ("813", "Florida"), ("850", "Florida"), ("863", "Florida"),
        ("904", "Florida"), ("941", "Florida"), ("954", "Florida"),
        ("229", "Georgia"), ("404", "Georgia"), ("470", "Georgia"), ("478", "Georgia"), ("678", "Georgia"),
        ("706", "Georgia"), ("762", "Georgia"), ("770", "Georgia"), ("912", "Georgia"), ("943", "Georgia"),
        ("808", "Hawaii"),
        ("208", "Idaho"), ("986", "Idaho"),
        ("217", "Illinois"), ("224", "Illinois"), ("309", "Illinois"), ("312", "Illinois"), ("331", "Illinois"),
        ("447", "Illinois"), ("618", "Illinois"), ("630", "Illinois"), ("708", "Illinois"), ("773", "Illinois"),
        ("779", "Illinois"), ("815", "Illinois"), ("847", "Illinois"), ("872", "Illinois"),
        ("219", "Indiana"), ("260", "Indiana"), ("317", "Indiana"), ("463", "Indiana"), ("574", "Indiana"),
        ("765", "Indiana"), ("812", "Indiana"), ("930", "Indiana"),
        ("319", "Iowa"), ("515", "Iowa"), ("563", "Iowa"), ("641", "Iowa"), ("712", "Iowa"),
        ("316", "Kansas"), ("620", "Kansas"), ("785", "Kansas"), ("913", "Kansas"),
        ("270", "Kentucky"), ("364", "Kentucky"), ("502", "Kentucky"), ("606", "Kentucky"), ("859", "Kentucky"),
        ("225", "Louisiana"), ("318", "Louisiana"), ("337", "Louisiana"), ("504", "Louisiana"), ("985", "Louisiana"),
        ("207", "Maine"),
        ("240", "Maryland"), ("301", "Maryland"), ("410", "Maryland"), ("443", "Maryland"), ("667", "Maryland"),
        ("339", "Massachusetts"), ("351", "Massachusetts"), ("413", "Massachusetts"), ("508", "Massachusetts"),
        ("617", "Massachusetts"), ("774", "Massachusetts"), ("781", "Massachusetts"), ("857", "Massachusetts"),
        ("978", "Massachusetts"),
        ("231", "Michigan"), ("248", "Michigan"), ("269", "Michigan"), ("313", "Michigan"), ("517", "Michigan"),
        ("586", "Michigan"), ("616", "Michigan"), ("734", "Michigan"), ("810", "Michigan"), ("906", "Michigan"),
        ("947", "Michigan"), ("989", "Michigan"),
        ("218", "Minnesota"), ("320", "Minnesota"), ("507", "Minnesota"), ("612", "Minnesota"), ("651", "Minnesota"),
        ("763", "Minnesota"), ("952", "Minnesota"),
        ("228", "Mississippi"), ("601", "Mississippi"), ("662", "Mississippi"), ("769", "Mississippi"),
        ("314", "Missouri"), ("417", "Missouri"), ("573", "Missouri"), ("636", "Missouri"), ("660", "Missouri"),
        ("816", "Missouri"),
        ("406", "Montana"),
        ("308", "Nebraska"), ("402", "Nebraska"), ("531", "Nebraska"),
        ("702", "Nevada"), ("725", "Nevada"), ("775", "Nevada"),
        ("603", "New Hampshire"),
        ("201", "New Jersey"), ("551", "New Jersey"), ("609", "New Jersey"), ("640", "New Jersey"),
        ("732", "New Jersey"), ("848", "New Jersey"), ("856", "New Jersey"), ("862", "New Jersey"),
        ("908", "New Jersey"), ("973", "New Jersey"),
        ("505", "New Mexico"), ("575", "New Mexico"),
        ("212", "New York"), ("315", "New York"), ("332", "New York"), ("347", "New York"), ("363", "New York"),
        ("516", "New York"), ("518", "New York"), ("585", "New York"), ("607", "New York"), ("631", "New York"),
        ("646", "New York"), ("680", "New York"), ("716", "New York"), ("718", "New York"), ("838", "New York"),
        ("845", "New York"), ("914", "New York"), ("917", "New York"), ("929", "New York"), ("934", "New York"),
        ("252", "North Carolina"), ("336", "North Carolina"), ("704", "North Carolina"), ("743", "North Carolina"),
        ("828", "North Carolina"), ("910", "North Carolina"), ("919", "North Carolina"), ("980", "North Carolina"),
        ("984", "North Carolina"),
        ("701", "North Dakota"),
        ("216", "Ohio"), ("220", "Ohio"), ("234", "Ohio"), ("283", "Ohio"), ("326", "Ohio"),
        ("330", "Ohio"), ("380", "Ohio"), ("419", "Ohio"), ("440", "Ohio"), ("513", "Ohio"),
        ("567", "Ohio"), ("614", "Ohio"), ("740", "Ohio"), ("937", "Ohio"),
        ("405", "Oklahoma"), ("539", "Oklahoma"), ("572", "Oklahoma"), ("580", "Oklahoma"), ("918", "Oklahoma"),
        ("458", "Oregon"), ("503", "Oregon"), ("541", "Oregon"), ("971", "Oregon"),
        ("215", "Pennsylvania"), ("223", "Pennsylvania"), ("267", "Pennsylvania"), ("272", "Pennsylvania"),
        ("412", "Pennsylvania"), ("445", "Pennsylvania"), ("484", "Pennsylvania"), ("570", "Pennsylvania"),
        ("610", "Pennsylvania"), ("717", "Pennsylvania"), ("724", "Pennsylvania"), ("814", "Pennsylvania"),
        ("878", "Pennsylvania"),
        ("401", "Rhode Island"),
        ("803", "South Carolina"), ("839", "South Carolina"), ("843", "South Carolina"), ("854", "South Carolina"),
        ("864", "South Carolina"),
        ("605", "South Dakota"),
        ("423", "Tennessee"), ("615", "Tennessee"), ("629", "Tennessee"), ("731", "Tennessee"), ("865", "Tennessee"),
        ("901", "Tennessee"), ("931", "Tennessee"),
        ("210", "Texas"), ("214", "Texas"), ("254", "Texas"), ("281", "Texas"), ("325", "Texas"),
        ("346", "Texas"), ("361", "Texas"), ("409", "Texas"), ("430", "Texas"), ("432", "Texas"),
        ("469", "Texas"), ("512", "Texas"), ("682", "Texas"), ("713", "Texas"), ("726", "Texas"),
        ("737", "Texas"), ("806", "Texas"), ("817", "Texas"), ("830", "Texas"), ("832", "Texas"),
        ("903", "Texas"), ("915", "Texas"), ("936", "Texas"), ("940", "Texas"), ("945", "Texas"),
        ("956", "Texas"), ("972", "Texas"), ("979", "Texas"),
        ("385", "Utah"), ("435", "Utah"), ("801", "Utah"),
        ("802", "Vermont"),
        ("276", "Virginia"), ("434", "Virginia"), ("540", "Virginia"), ("571", "Virginia"), ("703", "Virginia"),
        ("757", "Virginia"), ("804", "Virginia"),
        ("206", "Washington"), ("253", "Washington"), ("360", "Washington"), ("425", "Washington"),
        ("509", "Washington"), ("564", "Washington"),
        ("304", "West Virginia"), ("681", "West Virginia"),
        ("262", "Wisconsin"), ("414", "Wisconsin"), ("534", "Wisconsin"), ("608", "Wisconsin"),
        ("715", "Wisconsin"), ("920", "Wisconsin"),
        ("307", "Wyoming"),
        ("684", "American Samoa"), ("671", "Guam"), ("670", "Northern Mariana Islands"),
        ("787", "Puerto Rico"), ("939", "Puerto Rico"), ("340", "U.S. Virgin Islands"),
    ];

    /// <summary>
    /// ISO 3166-2 subdivisions for the initial trading countries (US + CA), Category
    /// = the country's alpha-2 code, Value = the bare postal abbreviation. Worldwide
    /// ISO 3166-2 (~5,000) is deliberately not seeded - tenants add what they need.
    /// </summary>
    internal static readonly (string Code, string Name, string Country, string Abbreviation)[] Subdivisions =
    [
        ("US-AL", "Alabama", "US", "AL"), ("US-AK", "Alaska", "US", "AK"), ("US-AZ", "Arizona", "US", "AZ"),
        ("US-AR", "Arkansas", "US", "AR"), ("US-CA", "California", "US", "CA"), ("US-CO", "Colorado", "US", "CO"),
        ("US-CT", "Connecticut", "US", "CT"), ("US-DE", "Delaware", "US", "DE"), ("US-FL", "Florida", "US", "FL"),
        ("US-GA", "Georgia", "US", "GA"), ("US-HI", "Hawaii", "US", "HI"), ("US-ID", "Idaho", "US", "ID"),
        ("US-IL", "Illinois", "US", "IL"), ("US-IN", "Indiana", "US", "IN"), ("US-IA", "Iowa", "US", "IA"),
        ("US-KS", "Kansas", "US", "KS"), ("US-KY", "Kentucky", "US", "KY"), ("US-LA", "Louisiana", "US", "LA"),
        ("US-ME", "Maine", "US", "ME"), ("US-MD", "Maryland", "US", "MD"), ("US-MA", "Massachusetts", "US", "MA"),
        ("US-MI", "Michigan", "US", "MI"), ("US-MN", "Minnesota", "US", "MN"), ("US-MS", "Mississippi", "US", "MS"),
        ("US-MO", "Missouri", "US", "MO"), ("US-MT", "Montana", "US", "MT"), ("US-NE", "Nebraska", "US", "NE"),
        ("US-NV", "Nevada", "US", "NV"), ("US-NH", "New Hampshire", "US", "NH"), ("US-NJ", "New Jersey", "US", "NJ"),
        ("US-NM", "New Mexico", "US", "NM"), ("US-NY", "New York", "US", "NY"), ("US-NC", "North Carolina", "US", "NC"),
        ("US-ND", "North Dakota", "US", "ND"), ("US-OH", "Ohio", "US", "OH"), ("US-OK", "Oklahoma", "US", "OK"),
        ("US-OR", "Oregon", "US", "OR"), ("US-PA", "Pennsylvania", "US", "PA"), ("US-RI", "Rhode Island", "US", "RI"),
        ("US-SC", "South Carolina", "US", "SC"), ("US-SD", "South Dakota", "US", "SD"), ("US-TN", "Tennessee", "US", "TN"),
        ("US-TX", "Texas", "US", "TX"), ("US-UT", "Utah", "US", "UT"), ("US-VT", "Vermont", "US", "VT"),
        ("US-VA", "Virginia", "US", "VA"), ("US-WA", "Washington", "US", "WA"), ("US-WV", "West Virginia", "US", "WV"),
        ("US-WI", "Wisconsin", "US", "WI"), ("US-WY", "Wyoming", "US", "WY"),
        ("US-DC", "District of Columbia", "US", "DC"),
        ("US-AS", "American Samoa", "US", "AS"), ("US-GU", "Guam", "US", "GU"),
        ("US-MP", "Northern Mariana Islands", "US", "MP"), ("US-PR", "Puerto Rico", "US", "PR"),
        ("US-VI", "U.S. Virgin Islands", "US", "VI"),
        ("CA-AB", "Alberta", "CA", "AB"), ("CA-BC", "British Columbia", "CA", "BC"), ("CA-MB", "Manitoba", "CA", "MB"),
        ("CA-NB", "New Brunswick", "CA", "NB"), ("CA-NL", "Newfoundland and Labrador", "CA", "NL"),
        ("CA-NS", "Nova Scotia", "CA", "NS"), ("CA-NT", "Northwest Territories", "CA", "NT"),
        ("CA-NU", "Nunavut", "CA", "NU"), ("CA-ON", "Ontario", "CA", "ON"),
        ("CA-PE", "Prince Edward Island", "CA", "PE"), ("CA-QC", "Quebec", "CA", "QC"),
        ("CA-SK", "Saskatchewan", "CA", "SK"), ("CA-YT", "Yukon", "CA", "YT"),
    ];

    /// <summary>Personal-name honorifics. Not data-locked: no logic evaluates them,
    /// and tenants legitimately add their own.</summary>
    internal static readonly (string Key, string Label)[] Honorifics =
    [
        ("Mr", "Mr."), ("Mrs", "Mrs."), ("Ms", "Ms."), ("Mx", "Mx."), ("Dr", "Dr."),
        ("Prof", "Prof."), ("Rev", "Rev."), ("Hon", "Hon."), ("Sir", "Sir"), ("Dame", "Dame"),
    ];

    /// <summary>Personal-name suffixes. Not data-locked, same reasoning as honorifics.</summary>
    internal static readonly (string Key, string Label)[] NameSuffixes =
    [
        ("Jr", "Jr."), ("Sr", "Sr."), ("II", "II"), ("III", "III"), ("IV", "IV"), ("V", "V"),
        ("MD", "M.D."), ("PhD", "Ph.D."), ("Esq", "Esq."), ("CPA", "CPA"),
    ];

    /// <summary>UN/CEFACT Recommendation 20 codes for the global.uom units. The
    /// UNIT KEY is the key (the map's whole point is key→code lookup); the Rec 20
    /// code is the machine Value. Package-type units (box, case, pack, pallet,
    /// roll) are ABSENT: those belong to Recommendation 21's package codes, and
    /// absence means "no Rec 20 code", never a borrowed one. Where Rec 20
    /// distinguishes US/imperial variants (pint, quart, gallon, short ton) the US
    /// code is used, matching the seed labels.</summary>
    internal static readonly (string UnitKey, string Code)[] UomRec20Codes =
    [
        // Count
        ("ea", "EA"), ("pr", "PR"), ("dz", "DZN"), ("gro", "GRO"), ("st", "SET"),
        // Mass
        ("mg", "MGM"), ("g", "GRM"), ("kg", "KGM"), ("t", "TNE"),
        ("oz", "ONZ"), ("lb", "LBR"), ("ton", "STN"),
        // Volume
        ("ml", "MLT"), ("cl", "CLT"), ("l", "LTR"), ("m3", "MTQ"),
        ("floz", "OZA"), ("pt", "PTL"), ("qt", "QTL"), ("gal", "GLL"), ("ft3", "FTQ"),
        // Length
        ("mm", "MMT"), ("cm", "CMT"), ("m", "MTR"), ("km", "KMT"),
        ("in", "INH"), ("ft", "FOT"), ("yd", "YRD"), ("mi", "SMI"),
        // Area
        ("m2", "MTK"), ("ha", "HAR"), ("ft2", "FTK"), ("ac", "ACR"),
        // Time
        ("s", "SEC"), ("min", "MIN"), ("hr", "HUR"), ("day", "DAY"),
        ("wk", "WEE"), ("mo", "MON"), ("yr", "ANN"),
        // Temperature
        ("cel", "CEL"), ("fah", "FAH"), ("kel", "KEL"),
    ];
}
