<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <AssemblyName>OrchardCore.Crest.Components</AssemblyName>
    <RootNamespace>Crest.Components</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Themes\**" />
    <Content Remove="Themes\**" />
    <EmbeddedResource Remove="Themes\**" />
    <None Remove="Themes\**" />
    <RazorGenerate Remove="Themes\**" />
    <RazorComponent Remove="Themes\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Radzen.Blazor" />
  </ItemGroup>
</Project>
