<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <OrchardCoreCompatibilityVersion>3.0.0</OrchardCoreCompatibilityVersion>
    <CrestSecurityPatch>0</CrestSecurityPatch>
    <CrestBugPatch>0</CrestBugPatch>
    <CrestVersion>$(OrchardCoreCompatibilityVersion).$(CrestSecurityPatch).$(CrestBugPatch)</CrestVersion>
    <VersionPrefix>$(OrchardCoreCompatibilityVersion)</VersionPrefix>
    <PackageVersion>$(OrchardCoreCompatibilityVersion)</PackageVersion>
    <AssemblyVersion>3.0.0.0</AssemblyVersion>
    <FileVersion>3.0.0.0</FileVersion>
    <AssemblyInformationalVersion>$(CrestVersion)</AssemblyInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Themes\**" />
    <Content Remove="Themes\**" />
    <EmbeddedResource Remove="Themes\**" />
    <None Remove="Themes\**" />
    <RazorGenerate Remove="Themes\**" />
    <RazorComponent Remove="Themes\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="OrchardCore.Admin.Abstractions" />
    <PackageReference Include="OrchardCore.AdminMenu" />
    <PackageReference Include="OrchardCore.AdminMenu.Abstractions" />
    <PackageReference Include="OrchardCore.ContentManagement" />
    <PackageReference Include="OrchardCore.Contents" />
    <PackageReference Include="OrchardCore.FileStorage.Abstractions" />
    <PackageReference Include="OrchardCore.Features" />
    <PackageReference Include="OrchardCore.Menu" />
    <PackageReference Include="OrchardCore.Media.Abstractions" />
    <PackageReference Include="OrchardCore.Media" />
    <PackageReference Include="OrchardCore.Module.Targets" />
    <PackageReference Include="OrchardCore.Recipes.Abstractions" />
    <PackageReference Include="OrchardCore.Recipes.Core" />
    <PackageReference Include="OrchardCore.Queries" />
    <PackageReference Include="OrchardCore.Localization.Core" />
    <PackageReference Include="OrchardCore.Localization" />
    <PackageReference Include="OrchardCore.Indexing.Abstractions" />
    <PackageReference Include="OrchardCore.Indexing.Core" />
    <PackageReference Include="OrchardCore.Lucene.Core" />
    <PackageReference Include="OrchardCore.Roles.Abstractions" />
    <PackageReference Include="OrchardCore.Themes" />
    <PackageReference Include="OrchardCore.Templates" />
    <PackageReference Include="OrchardCore.Tenants" />
    <PackageReference Include="OrchardCore.Security" />
    <PackageReference Include="OrchardCore.Users" />
    <PackageReference Include="YesSql.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrchardCore.Crest.Iconify\OrchardCore.Crest.Iconify.csproj" />
    <Compile Include="..\OrchardCore.Crest.Icons\Contracts\**\*.cs" Link="Icons\Contracts\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\OrchardCore.Crest.Icons\Providers\**\*.cs" Link="Icons\Providers\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\OrchardCore.Crest.Icons\Services\**\*.cs" Link="Icons\Services\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
