<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
    <AssemblyName>OrchardCore.Crest.Iconify</AssemblyName>
    <RootNamespace>Crest.Iconify</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="icons\Sources\IconifyCache\**" />
    <Content Remove="icons\Sources\IconifyCache\**" />
    <EmbeddedResource Remove="icons\Sources\IconifyCache\**" />
    <None Remove="icons\Sources\IconifyCache\**" />
    <Compile Remove="tests\**\*.cs" />
  </ItemGroup>
</Project>
